### ISSUE TITLE
两次断网重连 报错。 

### ISSUE THREAD

**Issue by qq380791741** [liu-xiao-dong/JD-Test#18]
Caused by: java.lang.IllegalArgumentException: view must not be null
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:281)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at com.sxjs.common.widget.NoNetWorkNotice.show(NoNetWorkNotice.java:58)
        at com.sxjs.common.receiver.NetWorkChangeBroadcastReceiver.onReceive(NetWorkChangeBroadcastReceiver.java:46)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1313)
        at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4) 
        at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494)

**Comment by liu-xiao-dong** [comment]
已修复，谢谢反馈
